Update patch set 1
Patch Set 1:

Dry run: Try jobs failed on following builders:
  luci.webrtc.try/win_x86_msvc_rel JOB_FAILED https://ci.chromium.org/b/8890088802694426336
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [14/209] CXX obj/audio/audio/audio_state.obj
    FAILED: obj/audio/audio/audio_state.obj
    ninja -t msvc -e environment.x86 -- "C:\b\s\w\ir\cache\builder\src\third_party\depot_tools\win_toolc...(too long)
    ../../audio/audio_state.cc(191): error C3493: 'kNumSamples' cannot be implicitly captured because no default capture mode has been specified
    ../../audio/audio_state.cc(191): error C3493: 'kNumChannels' cannot be implicitly captured because no default capture mode has been specified
    ../../audio/audio_state.cc(197): error C3493: 'kSamplesPerSecond' cannot be implicitly captured because no default capture mode has been specified
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output[failure_summary]

Patch-set: 1
Tag: autogenerated:cq:dry-run