Update patch set 7
Patch Set 7:

Dry run: Failed builds:
  luci.webrtc.try/win_x86_msvc_rel JOB_FAILED https://cr-buildbucket.appspot.com/build/8846147707581760896
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [12/99] CXX obj/net/dcsctp/fuzzers/dcsctp_fuzzers/dcsctp_fuzzers.obj
    FAILED: obj/net/dcsctp/fuzzers/dcsctp_fuzzers/dcsctp_fuzzers.obj
    ninja -t msvc -e environment.x86 -- "C:\b\s\w\ir\cache\builder\src\third_party\depot_tools\win_toolc...(too long)
    ../..\net/dcsctp/public/dcsctp_options.h(88): error C2397: conversion from 'double' to 'size_t' requires a narrowing conversion
    [18/99] CXX obj/net/dcsctp/packet/dcsctp_packet_unittests/sctp_packet_test.obj
    FAILED: obj/net/dcsctp/packet/dcsctp_packet_unittests/sctp_packet_test.obj
    ninja -t msvc -e environment.x86 -- "C:\b\s\w\ir\cache\builder\src\third_party\depot_tools\win_toolc...(too long)
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output[failure_summary]

Patch-set: 7
Tag: autogenerated:cq:dry-run