Update patch set 1
Patch Set 1:

Failed builds:
  luci.webrtc.try/android_compile_x64_dbg JOB_FAILED https://cr-buildbucket.appspot.com/build/8850678564288867872
    #### Step _generate_build_files_ failed. Error logs are shown below:
    ```
    ERROR at //build/config/android/rules.gni:3923:29: Assignment had no effect.
          enable_native_mocks = true
                                ^---
    You set the variable "enable_native_mocks" here and it was unused before it went
    out of scope.
    See //build/config/android/rules.gni:3918:5: whence it was called.
        android_apk(target_name) {
        ^-------------------------
    See //testing/test.gni:185:7: whence it was called.
          unittest_apk(_apk_target) {
          ^--------------------------
    See //webrtc.gni:443:3: whence it was called.
      test(target_name) {
      ^------------------
    See //BUILD.gn:532:3: whence it was called.
      rtc_test("rtc_unittests") {
      ^--------------------------
    ```
    #### More information can be found in the stdout.
  luci.webrtc.try/android_arm_rel JOB_FAILED https://cr-buildbucket.appspot.com/build/8850678564288867936
    #### Step _generate_build_files_ failed. Error logs are shown below:
    ```
    ERROR at //build/config/android/rules.gni:3923:29: Assignment had no effect.
          enable_native_mocks = true
                                ^---
    You set the variable "enable_native_mocks" here and it was unused before it went
    out of scope.
    See //build/config/android/rules.gni:3918:5: whence it was called.
        android_apk(target_name) {
        ^-------------------------
    See //testing/test.gni:185:7: whence it was called.
          unittest_apk(_apk_target) {
          ^--------------------------
    See //webrtc.gni:443:3: whence it was called.
      test(target_name) {
      ^------------------
    See //BUILD.gn:532:3: whence it was called.
      rtc_test("rtc_unittests") {
      ^--------------------------
    ```
    #### More information can be found in the stdout.
  luci.webrtc.try/mac_asan JOB_FAILED https://cr-buildbucket.appspot.com/build/8850678564288867472
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [452/5656] CXX obj/common_video/common_video/webrtc_libyuv.o
    FAILED: obj/common_video/common_video/webrtc_libyuv.o
    /opt/s/w/ir/cache/goma/client/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -...(too long)
    In file included from ../../common_video/libyuv/webrtc_libyuv.cc:18:
    In file included from ../../third_party/libyuv/include/libyuv.h:25:
    ../../third_party/libyuv/include/libyuv/row.h:750:5: error: 'LIBYUV_UNLIMITED_DATA' is not defined, evaluates to 0 [-Werror,-Wundef]
    #if LIBYUV_UNLIMITED_DATA
    ^
    1 error generated.
    ```
    #### More information in raw_io.output[failure_summary]
  luci.webrtc.try/linux_asan JOB_FAILED https://cr-buildbucket.appspot.com/build/8850678564288867760
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [97/5603] CXX obj/common_video/common_video/webrtc_libyuv.o
    FAILED: obj/common_video/common_video/webrtc_libyuv.o
    /b/s/w/ir/cache/goma/client/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF...(too long)
    In file included from ../../common_video/libyuv/webrtc_libyuv.cc:18:
    In file included from ../../third_party/libyuv/include/libyuv.h:25:
    ../../third_party/libyuv/include/libyuv/row.h:750:5: error: 'LIBYUV_UNLIMITED_DATA' is not defined, evaluates to 0 [-Werror,-Wundef]
    #if LIBYUV_UNLIMITED_DATA
    ^
    1 error generated.
    ```
    #### More information in raw_io.output[failure_summary]
  luci.webrtc.try/linux_msan JOB_FAILED https://cr-buildbucket.appspot.com/build/8850678564288867584
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [1245/5814] CXX obj/common_video/common_video/webrtc_libyuv.o
    FAILED: obj/common_video/common_video/webrtc_libyuv.o
    /b/s/w/ir/cache/goma/client/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF...(too long)
    In file included from ../../common_video/libyuv/webrtc_libyuv.cc:18:
    In file included from ../../third_party/libyuv/include/libyuv.h:25:
    ../../third_party/libyuv/include/libyuv/row.h:750:5: error: 'LIBYUV_UNLIMITED_DATA' is not defined, evaluates to 0 [-Werror,-Wundef]
    #if LIBYUV_UNLIMITED_DATA
    ^
    1 error generated.
    ```
    #### More information in raw_io.output[failure_summary]
  luci.webrtc.try/mac_rel JOB_FAILED https://cr-buildbucket.appspot.com/build/8850678564288867424
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [460/5648] OBJCXX obj/sdk/videoframebuffer_objc/RTCCVPixelBuffer.o
    FAILED: obj/sdk/videoframebuffer_objc/RTCCVPixelBuffer.o
    /opt/s/w/ir/cache/goma/client/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -...(too long)
    In file included from ../../sdk/objc/components/video_frame_buffer/RTCCVPixelBuffer.mm:18:
    In file included from ../../third_party/libyuv/include/libyuv.h:25:
    ../../third_party/libyuv/include/libyuv/row.h:750:5: error: 'LIBYUV_UNLIMITED_DATA' is not defined, evaluates to 0 [-Werror,-Wundef]
    #if LIBYUV_UNLIMITED_DATA
    ^
    1 error generated.
    ```
    #### More information in raw_io.output[failure_summary]
  luci.webrtc.try/android_compile_x86_dbg JOB_FAILED https://cr-buildbucket.appspot.com/build/8850678564288867856
    #### Step _generate_build_files_ failed. Error logs are shown below:
    ```
    ERROR at //build/config/android/rules.gni:3923:29: Assignment had no effect.
          enable_native_mocks = true
                                ^---
    You set the variable "enable_native_mocks" here and it was unused before it went
    out of scope.
    See //build/config/android/rules.gni:3918:5: whence it was called.
        android_apk(target_name) {
        ^-------------------------
    See //testing/test.gni:185:7: whence it was called.
          unittest_apk(_apk_target) {
          ^--------------------------
    See //webrtc.gni:443:3: whence it was called.
      test(target_name) {
      ^------------------
    See //BUILD.gn:532:3: whence it was called.
      rtc_test("rtc_unittests") {
      ^--------------------------
    ```
    #### More information can be found in the stdout.
  luci.webrtc.try/linux_more_configs JOB_FAILED https://cr-buildbucket.appspot.com/build/8850678564288867600
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [1142/6165] CXX obj/common_video/common_video/webrtc_libyuv.o
    FAILED: obj/common_video/common_video/webrtc_libyuv.o
    /b/s/w/ir/cache/goma/client/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF...(too long)
    In file included from ../../common_video/libyuv/webrtc_libyuv.cc:18:
    In file included from ../../third_party/libyuv/include/libyuv.h:25:
    ../../third_party/libyuv/include/libyuv/row.h:750:5: error: 'LIBYUV_UNLIMITED_DATA' is not defined, evaluates to 0 [-Werror,-Wundef]
    #if LIBYUV_UNLIMITED_DATA
    ^
    1 error generated.
    ```
    #### More information in raw_io.output[failure_summary]
  luci.webrtc.try/android_compile_arm64_rel JOB_FAILED https://cr-buildbucket.appspot.com/build/8850678564288867904
    #### Step _generate_build_files_ failed. Error logs are shown below:
    ```
    ERROR at //build/config/android/rules.gni:3923:29: Assignment had no effect.
          enable_native_mocks = true
                                ^---
    You set the variable "enable_native_mocks" here and it was unused before it went
    out of scope.
    See //build/config/android/rules.gni:3918:5: whence it was called.
        android_apk(target_name) {
        ^-------------------------
    See //testing/test.gni:185:7: whence it was called.
          unittest_apk(_apk_target) {
          ^--------------------------
    See //webrtc.gni:443:3: whence it was called.
      test(target_name) {
      ^------------------
    See //BUILD.gn:532:3: whence it was called.
      rtc_test("rtc_unittests") {
      ^--------------------------
    ```
    #### More information can be found in the stdout.
  luci.webrtc.try/android_arm_more_configs JOB_FAILED https://cr-buildbucket.appspot.com/build/8850678564288867952
    #### Step _generate_build_files_ failed. Error logs are shown below:
    ```
    ERROR at //build/config/android/rules.gni:3923:29: Assignment had no effect.
          enable_native_mocks = true
                                ^---
    You set the variable "enable_native_mocks" here and it was unused before it went
    out of scope.
    See //build/config/android/rules.gni:3918:5: whence it was called.
        android_apk(target_name) {
        ^-------------------------
    See //testing/test.gni:185:7: whence it was called.
          unittest_apk(_apk_target) {
          ^--------------------------
    See //webrtc.gni:443:3: whence it was called.
      test(target_name) {
      ^------------------
    See //BUILD.gn:532:3: whence it was called.
      rtc_test("rtc_unittests") {
      ^--------------------------
    ```
    #### More information can be found in the stdout.

Patch-set: 1
Tag: autogenerated:cq:full-run