Update patch set 1
Patch Set 1:

Failed builds:
  luci.webrtc.try/android_arm_dbg JOB_FAILED https://cr-buildbucket.appspot.com/build/8850829578908184304
    #### Step _generate_build_files_ failed. Error logs are shown below:
    ```
    ERROR at //build/config/android/rules.gni:3923:29: Assignment had no effect.
          enable_native_mocks = true
                                ^---
    You set the variable "enable_native_mocks" here and it was unused before it went
    out of scope.
    See //build/config/android/rules.gni:3918:5: whence it was called.
        android_apk(target_name) {
        ^-------------------------
    See //testing/test.gni:185:7: whence it was called.
          unittest_apk(_apk_target) {
          ^--------------------------
    See //webrtc.gni:443:3: whence it was called.
      test(target_name) {
      ^------------------
    See //BUILD.gn:532:3: whence it was called.
      rtc_test("rtc_unittests") {
      ^--------------------------
    ```
    #### More information can be found in the stdout.
  luci.webrtc.try/mac_compile_dbg JOB_FAILED https://cr-buildbucket.appspot.com/build/8850829578908183776
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [46/5556] OBJCXX obj/sdk/videoframebuffer_objc/RTCCVPixelBuffer.o
    FAILED: obj/sdk/videoframebuffer_objc/RTCCVPixelBuffer.o
    /opt/s/w/ir/cache/goma/client/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -...(too long)
    In file included from ../../sdk/objc/components/video_frame_buffer/RTCCVPixelBuffer.mm:18:
    In file included from ../../third_party/libyuv/include/libyuv.h:25:
    ../../third_party/libyuv/include/libyuv/row.h:750:5: error: 'LIBYUV_UNLIMITED_DATA' is not defined, evaluates to 0 [-Werror,-Wundef]
    #if LIBYUV_UNLIMITED_DATA
    ^
    1 error generated.
    ```
    #### More information in raw_io.output[failure_summary]

Patch-set: 1
Tag: autogenerated:cq:full-run