Update patch set 1
Patch Set 1:

Dry run: Failed builds:
  luci.webrtc.try/win_x86_msvc_rel JOB_FAILED https://cr-buildbucket.appspot.com/build/8850754820406678816
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [91/1135] CXX obj/net/dcsctp/packet/sctp_packet/sctp_packet.obj
    FAILED: obj/net/dcsctp/packet/sctp_packet/sctp_packet.obj
    ninja -t msvc -e environment.x86 -- "C:\b\s\w\ir\cache\builder\src\third_party\depot_tools\win_toolc...(too long)
    ../../net/dcsctp/packet/sctp_packet.cc(86): error C7555: use of designated initializers requires at least '/std:c++latest'
    [108/1135] CXX obj/net/dcsctp/timer/timer/timer.obj
    FAILED: obj/net/dcsctp/timer/timer/timer.obj
    ninja -t msvc -e environment.x86 -- "C:\b\s\w\ir\cache\builder\src\third_party\depot_tools\win_toolc...(too long)
    ../../net/dcsctp/timer/timer.cc(34): error C2220: the following warning is treated as an error
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output[failure_summary]
  luci.webrtc.try/win_x86_msvc_dbg JOB_FAILED https://cr-buildbucket.appspot.com/build/8850754820406678832
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [65/1135] CXX obj/net/dcsctp/timer/timer/timer.obj
    FAILED: obj/net/dcsctp/timer/timer/timer.obj
    ninja -t msvc -e environment.x86 -- "C:\b\s\w\ir\cache\builder\src\third_party\depot_tools\win_toolc...(too long)
    ../../net/dcsctp/timer/timer.cc(34): error C2220: the following warning is treated as an error
    ../../net/dcsctp/timer/timer.cc(34): warning C4334: '<<': result of 32-bit shift implicitly converted to 64 bits (was 64-bit shift intended?)
    [75/1135] CXX obj/net/dcsctp/packet/sctp_packet/sctp_packet.obj
    FAILED: obj/net/dcsctp/packet/sctp_packet/sctp_packet.obj
    ninja -t msvc -e environment.x86 -- "C:\b\s\w\ir\cache\builder\src\third_party\depot_tools\win_toolc...(too long)
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output[failure_summary]

Patch-set: 1
Tag: autogenerated:cq:dry-run