Update patch set 8
Patch Set 8:

The gcc build bot produces the following warning 8Which is then treated as an error),

In file included from ../../modules/rtp_rtcp/source/rtp_sender_video.cc:11:0:
../../modules/rtp_rtcp/source/rtp_sender_video.h:45:43: error: declaration of 'virtual webrtc::VideoCodecType webrtc::RTPSenderVideo::VideoCodecType() const' [-fpermissive]
   virtual VideoCodecType VideoCodecType() const;
                                           ^
In file included from ../../modules/rtp_rtcp/source/rtp_sender_video.h:18:0,
                 from ../../modules/rtp_rtcp/source/rtp_sender_video.cc:11:
../../common_types.h:407:6: error: changes meaning of 'VideoCodecType' from 'enum webrtc::VideoCodecType' [-fpermissive]
 enum VideoCodecType {
      ^

And according to gcc docs, -fpermissive only warns about non-conforming code. Is it invalid in C++ to have a method name that collides with an enum type? Then the method has to be renamed. (Personally, I think C style with explicit "enum", "struct" etc and the coresponding type tags in their own namespace was a good thing). Hmm, or maybe in this case just adding enum on the return type is enough?

I'm a bit confused, but I'll try that out.

Patch-set: 8
Reviewer: Gerrit User 5234 <5234@58829da1-049c-39fb-b951-ebdcd0984767>
Label: Commit-Queue=0