Fix generate_buildbot_json.
When running it, even without changes at HEAD I got:

```
KeyError: 'ios_runtime_cache_17_0'
```

This CL moves `ios_runtime_cache_17_0` to infra/specs/mixins.pyl and
includes the changes of running generate_buildbot_json.

Bug: b/325441006
Change-Id: I7ea236ccc1f7439d7750208260b01d7636db4ae5