Update patch set 6
Patch Set 6:

(5 comments)

Looks like androidnativeapi also needs to be updated:

../../examples/androidnativeapi/jni/androidcallclient.cc:157:7: error: no matching function for call to 'Create'
        cricket::WebRtcMediaEngineFactory::Create(
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  ../../media/engine/webrtcmediaengine.h:46:32: note: candidate function not viable: requires 6 arguments, but 7 were provided
    static MediaEngineInterface* Create(

Patch-set: 6
Reviewer: Gerrit User 5023 <5023@58829da1-049c-39fb-b951-ebdcd0984767>
Label: Commit-Queue=0