Fix no_exit_time_destructors in pc.
This CL fixes the following error:
pc/peerconnection.cc:396:7:
error: declaration requires an exit-time destructor
[-Werror,-Wexit-time-destructors]
      proto_media_counter_map = {

It moves the protocol to media map into PeerConnection's attributes, the
map is initialized during PeerConnection::Initialize.
This removes the need of using 'static' and it should not cause too much
overhead since the map is initialized only once for each PeerConnection.

Bug: webrtc:9693
Change-Id: Icd71a70204ccc6fb032af52c64afa59e9aa7af74