Update patch set 2
Patch Set 2:

Dry run: Failed builds:
  luci.webrtc.try/win_x86_msvc_rel JOB_FAILED https://cr-buildbucket.appspot.com/build/8869105088141986480
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [274/2349] CXX obj/rtc_base/function_unittest/function_unittest.obj
    FAILED: obj/rtc_base/function_unittest/function_unittest.obj
    ninja -t msvc -e environment.x86 -- "C:\b\s\w\ir\cache\builder\src\third_party\depot_tools\win_toolc...(too long)
    ../..\rtc_base/function.h(131): error C7555: use of designated initializers requires at least '/std:c++latest'
    ../../rtc_base/function_unittest.cc(37): note: see reference to function template instantiation 'webrtc::UntypedFunction webrtc::UntypedFunction::Create<int(int)>(Signature (__cdecl *))' being compiled
    with
    [
    Signature=int (int)
    ]
    ```
    #### More information in raw_io.output[failure_summary]

Patch-set: 2
Tag: autogenerated:cq:dry-run