Do not build h264 on Linux32 Debug bots.
Setting ffmpeg_branding = "Chrome" is what causes a compilation error
(see [1], where h264_cabac.c is included):
../../third_party/ffmpeg/libavcodec/x86/cabac.h:193:9: error: inline assembly requires more registers than available
        BRANCHLESS_GET_CABAC("%0", "%q0", "(%4)", "%1", "%w1",
[...]

See: https://build.chromium.org/p/tryserver.webrtc/builders/linux32_dbg/builds/50.


Also, from the compililation error, this might be a bug on clang?

...
clang: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
...


[1] https://cs.chromium.org/chromium/src/third_party/ffmpeg/ffmpeg_generated.gni?l=222


Bug: webrtc:7413
Change-Id: I5c785d8f6f61c72a5e7665367023fec017b18d3e