Update patch set 7
Patch Set 7:

Dry run: Failed builds:
  luci.webrtc.try/linux_ubsan_vptr JOB_FAILED https://cr-buildbucket.appspot.com/build/8842451443863473968
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [2369/6414] CXX obj/modules/desktop_capture/primitives/desktop_region.o
    FAILED: obj/modules/desktop_capture/primitives/desktop_region.o
    /b/s/w/ir/cache/goma/client/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF...(too long)
    ../../modules/desktop_capture/desktop_region.cc:151:3: error: invalid operands to binary expression ('::rtc::webrtc_checks_impl::LogStreamer<>' and 'Rows::iterator' (aka '__map_iterator<__tree_iterator<std::__value_type<int, webrtc::DesktopRegion::Row *>, std::__tree_node<std::__value_type<int, webrtc::DesktopRegion::Row *>, void *> *, long>>'))
    RTC_DCHECK_NE(row, rows_.end());
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output[failure_summary]
  luci.webrtc.try/ios_compile_arm64_rel JOB_FAILED https://cr-buildbucket.appspot.com/build/8842451443863474272
    #### Step _analyze_ failed. Error logs are shown below:
    ```
    ERROR at //sdk/BUILD.gn:1051:11: Replacing nonempty list.
              defines = [ "GLES_SILENCE_DEPRECATION" ]
              ^------
    This overwrites a previously-defined nonempty list with another nonempty list.
    See //sdk/BUILD.gn:1047:21: for previous definition
              defines = [ "GLES_SILENCE_DEPRECATION" ]
                        ^----------------------------
    Did you mean to append/modify instead? If you really want to overwrite, do:
      foo = []
    before reassigning.
    See //BUILD.gn:477:7: which caused the file to be included.
          "sdk",
          ^----
    ```
    #### More information can be found in the stdout.
  luci.webrtc.try/linux_tsan2 JOB_FAILED https://cr-buildbucket.appspot.com/build/8842451443863474000
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [267/1660] CXX obj/examples/peerconnection_server/peer_channel.o
    FAILED: obj/examples/peerconnection_server/peer_channel.o
    /b/s/w/ir/cache/goma/client/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF...(too long)
    In file included from ../../examples/peerconnection/server/peer_channel.cc:20:
    In file included from ../../rtc_base/checks.h:59:
    ../../rtc_base/numerics/safe_compare.h:141:27: error: comparison between pointer and integer ('DataSocket *' and 'long')
    RTC_SAFECMP_MAKE_OP(EqOp, ==)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~
    ../../rtc_base/numerics/safe_compare.h:138:16: note: expanded from macro 'RTC_SAFECMP_MAKE_OP'
    return a op b;                       \
    ~ ^  ~
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output[failure_summary]
  luci.webrtc.try/ios_compile_arm64_dbg JOB_FAILED https://cr-buildbucket.appspot.com/build/8842451443863474288
    #### Step _analyze_ failed. Error logs are shown below:
    ```
    ERROR at //sdk/BUILD.gn:1051:11: Replacing nonempty list.
              defines = [ "GLES_SILENCE_DEPRECATION" ]
              ^------
    This overwrites a previously-defined nonempty list with another nonempty list.
    See //sdk/BUILD.gn:1047:21: for previous definition
              defines = [ "GLES_SILENCE_DEPRECATION" ]
                        ^----------------------------
    Did you mean to append/modify instead? If you really want to overwrite, do:
      foo = []
    before reassigning.
    See //BUILD.gn:477:7: which caused the file to be included.
          "sdk",
          ^----
    ```
    #### More information can be found in the stdout.
  luci.webrtc.try/ios_sim_x64_dbg_ios12 JOB_FAILED https://cr-buildbucket.appspot.com/build/8842451443863474256
    #### Step _analyze_ failed. Error logs are shown below:
    ```
    ERROR at //sdk/BUILD.gn:1051:11: Replacing nonempty list.
              defines = [ "GLES_SILENCE_DEPRECATION" ]
              ^------
    This overwrites a previously-defined nonempty list with another nonempty list.
    See //sdk/BUILD.gn:1047:21: for previous definition
              defines = [ "GLES_SILENCE_DEPRECATION" ]
                        ^----------------------------
    Did you mean to append/modify instead? If you really want to overwrite, do:
      foo = []
    before reassigning.
    See //BUILD.gn:477:7: which caused the file to be included.
          "sdk",
          ^----
    ```
    #### More information can be found in the stdout.

Patch-set: 7
Tag: autogenerated:cv