Update patch set 6
Patch Set 6:

Since the version with duplicated JNI_FUNCTION_ALIGN macro definition in jni_generator_helpers.h and jni_helpers.h fails to build locally:
../../../third_party/llvm-build/Release+Asserts/bin/clang++ 
...
obj/sdk/android/peerconnection_jni/rtc_certificate.o
  In file included from ../../../sdk/android/src/jni/pc/rtc_certificate.cc:17:
  In file included from gen/sdk/android/generated_peerconnection_jni/RtcCertificatePem_jni.h:16:
  gen/sdk/android/generated_peerconnection_jni/../../../../../../../sdk/android/src/jni/jni_generator_helper.h:28:9: error: 'JNI_FUNCTION_ALIGN' macro redefined [-Werror,-Wmacro-redefined]
  #define JNI_FUNCTION_ALIGN __attribute__((force_align_arg_pointer))
          ^
  ../../../sdk/android/src/jni/jni_helpers.h:30:9: note: previous definition is here
  #define JNI_FUNCTION_ALIGN
          ^
  1 error generated,
so I decided to submit CL without its explicit definition at all.

Patch-set: 6