Update patch set 1
Patch Set 1:

Dry run: Failed builds:
  luci.webrtc.try/win_x64_msvc_dbg JOB_FAILED https://cr-buildbucket.appspot.com/build/8850754853100566448
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [95/1151] CXX obj/net/dcsctp/packet/sctp_packet/sctp_packet.obj
    FAILED: obj/net/dcsctp/packet/sctp_packet/sctp_packet.obj
    ninja -t msvc -e environment.x64 -- "C:\b\s\w\ir\cache\builder\src\third_party\depot_tools\win_toolc...(too long)
    ../../net/dcsctp/packet/sctp_packet.cc(86): error C7555: use of designated initializers requires at least '/std:c++latest'
    [107/1151] CXX obj/net/dcsctp/timer/timer/timer.obj
    FAILED: obj/net/dcsctp/timer/timer/timer.obj
    ninja -t msvc -e environment.x64 -- "C:\b\s\w\ir\cache\builder\src\third_party\depot_tools\win_toolc...(too long)
    ../../net/dcsctp/timer/timer.cc(34): error C2220: the following warning is treated as an error
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output[failure_summary]

Patch-set: 1
Tag: autogenerated:cq:dry-run