Update patch set 5
Patch Set 5:

Dry run: Try jobs failed on following builders:
  luci.webrtc.try/win_x86_msvc_dbg JOB_FAILED https://ci.chromium.org/b/8895444080628599968
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [133/478] CXX obj/modules/audio_processing/aec3/aec3_unittests/alignment_mixer_unittest.obj
    FAILED: obj/modules/audio_processing/aec3/aec3_unittests/alignment_mixer_unittest.obj
    ninja -t msvc -e environment.x86 -- "C:\b\s\w\ir\cache\builder\src\third_party\depot_tools\win_toolc...(too long)
    ../../modules/audio_processing/aec3/alignment_mixer_unittest.cc(57): error C3493: 'kChannelOffset' cannot be implicitly captured because no default capture mode has been specified
    ../../modules/audio_processing/aec3/alignment_mixer_unittest.cc(64): error C2064: term does not evaluate to a function taking 2 arguments
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output[failure_summary]

Patch-set: 5
Tag: autogenerated:cq:dry-run