Fix cast of const-qualified types in FunctionThatDoesNothingImpl
Recent Clang versions fixed a bug which had previously allowed some casts that
removed qualifiers to go undiagnosed.

This fixes the following kind of error:

  ./../third_party/webrtc/api/optional.h:41:35: error: reinterpret_cast from
        'const int *' to 'void *' casts away qualifiers
	FunctionThatDoesNothingImpl(reinterpret_cast<void*>(x)));
				    ^~~~~~~~~~~~~~~~~~~~~~~~~~
  ../../third_party/webrtc/api/optional.h:280:45: note: in instantiation of
      function template specialization
      'rtc::optional_internal::FunctionThatDoesNothing<const int>' requested here
      return has_value_ ? *optional_internal::FunctionThatDoesNothing(&value_)
					      ^
  ../../third_party/webrtc/call/rtp_bitrate_configurator.cc:70:53:

        note: in instantiation of member function 'rtc::Optional<int>::value_or'
        requested here
	std::max(bitrate_config_mask_.min_bitrate_bps.value_or(0),
                                                    ^
Bug: chromium:831081
Change-Id: I032ebd1f052fa2a50548e984febb7fa462df42ea