Update patch set 1
Patch Set 1:

This CL has failed the run. Reason:

Failed Tryjobs:
* [webrtc/try/android_arm64_rel](https://cr-buildbucket.appspot.com/build/8757287750116745665). Summary [(view all results)](https://webrtc-review.googlesource.com/c/337283?checksPatchset=1&tab=checks):

---
#### Step _compile_ failed. Error logs are shown below:
```
[889/8183] CXX obj/sdk/android/base_jni/scoped_java_ref_counted.o
FAILED: obj/sdk/android/base_jni/scoped_java_ref_counted.o
../../buildtools/reclient/rewrapper -cfg=../../buildtools/reclient_cfgs/chromium-browser-clang/rewra...(too long)
../../sdk/android/src/jni/scoped_java_ref_counted.cc:22:3: error: no matching function for call to 'Java_RefCounted_retain'
22 |   Java_RefCounted_retain(jni, j_object);
|   ^~~~~~~~~~~~~~~~~~~~~~
```
##### ...The message was too long...
#### More information in raw_io.output_text[failure_summary]

---
* [webrtc/try/android_arm_more_configs](https://cr-buildbucket.appspot.com/build/8757287750116745633). Summary [(view all results)](https://webrtc-review.googlesource.com/c/337283?checksPatchset=1&tab=checks):

---
#### Step _compile_ failed. Error logs are shown below:
```
[912/7015] CXX obj/sdk/android/base_jni/scoped_java_ref_counted.o
FAILED: obj/sdk/android/base_jni/scoped_java_ref_counted.o
../../buildtools/reclient/rewrapper -cfg=../../buildtools/reclient_cfgs/chromium-browser-clang/rewra...(too long)
../../sdk/android/src/jni/scoped_java_ref_counted.cc:22:3: error: no matching function for call to 'Java_RefCounted_retain'
22 |   Java_RefCounted_retain(jni, j_object);
|   ^~~~~~~~~~~~~~~~~~~~~~
```
##### ...The message was too long...
#### More information in raw_io.output_text[failure_summary]

---
* [webrtc/try/android_compile_arm64_rel](https://cr-buildbucket.appspot.com/build/8757287750116745601). Summary [(view all results)](https://webrtc-review.googlesource.com/c/337283?checksPatchset=1&tab=checks):

---
#### Step _compile_ failed. Error logs are shown below:
```
[1945/7789] CXX obj/sdk/android/base_jni/scoped_java_ref_counted.o
FAILED: obj/sdk/android/base_jni/scoped_java_ref_counted.o
../../buildtools/reclient/rewrapper -cfg=../../buildtools/reclient_cfgs/chromium-browser-clang/rewra...(too long)
../../sdk/android/src/jni/scoped_java_ref_counted.cc:22:3: error: no matching function for call to 'Java_RefCounted_retain'
22 |   Java_RefCounted_retain(jni, j_object);
|   ^~~~~~~~~~~~~~~~~~~~~~
```
##### ...The message was too long...
#### More information in raw_io.output_text[failure_summary]

---
* [webrtc/try/android_compile_arm_rel](https://cr-buildbucket.appspot.com/build/8757287750116745585). Summary [(view all results)](https://webrtc-review.googlesource.com/c/337283?checksPatchset=1&tab=checks):

---
#### Step _compile_ failed. Error logs are shown below:
```
[2410/7804] CXX obj/sdk/android/base_jni/scoped_java_ref_counted.o
FAILED: obj/sdk/android/base_jni/scoped_java_ref_counted.o
../../buildtools/reclient/rewrapper -cfg=../../buildtools/reclient_cfgs/chromium-browser-clang/rewra...(too long)
../../sdk/android/src/jni/scoped_java_ref_counted.cc:22:3: error: no matching function for call to 'Java_RefCounted_retain'
22 |   Java_RefCounted_retain(jni, j_object);
|   ^~~~~~~~~~~~~~~~~~~~~~
```
##### ...The message was too long...
#### More information in raw_io.output_text[failure_summary]

---
* [webrtc/try/android_compile_x64_dbg](https://cr-buildbucket.appspot.com/build/8757287750116745569). Summary [(view all results)](https://webrtc-review.googlesource.com/c/337283?checksPatchset=1&tab=checks):

---
#### Step _compile_ failed. Error logs are shown below:
```
[1043/7541] CXX obj/sdk/android/native_api_jni/application_context_provider.o
FAILED: obj/sdk/android/native_api_jni/application_context_provider.o
../../buildtools/reclient/rewrapper -cfg=../../buildtools/reclient_cfgs/chromium-browser-clang/rewra...(too long)
../../sdk/android/native_api/jni/application_context_provider.cc:18:10: error: no matching conversion for functional-style cast from 'jni_zero::ScopedJavaLocalRef<jobject>' (aka 'ScopedJavaLocalRef<_jobject *>') to 'ScopedJavaLocalRef<jobject>' (aka 'ScopedJavaLocalRef<_jobject *>')
18 |   return ScopedJavaLocalRef<jobject>(
|          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
19 |       jni::Java_ApplicationContextProvider_getApplicationContext(jni));
```
##### ...The message was too long...
#### More information in raw_io.output_text[failure_summary]

---
* [webrtc/try/android_compile_x86_dbg](https://cr-buildbucket.appspot.com/build/8757287734652209681). Summary [(view all results)](https://webrtc-review.googlesource.com/c/337283?checksPatchset=1&tab=checks):

---
#### Step _compile_ failed. Error logs are shown below:
```
[2698/8029] CXX obj/sdk/android/base_jni/scoped_java_ref_counted.o
FAILED: obj/sdk/android/base_jni/scoped_java_ref_counted.o
../../buildtools/reclient/rewrapper -cfg=../../buildtools/reclient_cfgs/chromium-browser-clang/rewra...(too long)
../../sdk/android/src/jni/scoped_java_ref_counted.cc:22:3: error: no matching function for call to 'Java_RefCounted_retain'
22 |   Java_RefCounted_retain(jni, j_object);
|   ^~~~~~~~~~~~~~~~~~~~~~
```
##### ...The message was too long...
#### More information in raw_io.output_text[failure_summary]

---
* [webrtc/try/android_compile_x86_rel](https://cr-buildbucket.appspot.com/build/8757287750116745553). Summary [(view all results)](https://webrtc-review.googlesource.com/c/337283?checksPatchset=1&tab=checks):

---
#### Step _compile_ failed. Error logs are shown below:
```
[917/7548] CXX obj/sdk/android/base_jni/scoped_java_ref_counted.o
FAILED: obj/sdk/android/base_jni/scoped_java_ref_counted.o
../../buildtools/reclient/rewrapper -cfg=../../buildtools/reclient_cfgs/chromium-browser-clang/rewra...(too long)
../../sdk/android/src/jni/scoped_java_ref_counted.cc:22:3: error: no matching function for call to 'Java_RefCounted_retain'
22 |   Java_RefCounted_retain(jni, j_object);
|   ^~~~~~~~~~~~~~~~~~~~~~
```
##### ...The message was too long...
#### More information in raw_io.output_text[failure_summary]

---
* [webrtc/try/linux_rel](https://cr-buildbucket.appspot.com/build/8757288114135769073). Summary [(view all results)](https://webrtc-review.googlesource.com/c/337283?checksPatchset=1&tab=checks):

---
1 Test Suite(s) failed.

**modules_unittests** failed because of:

- LibaomAv1Test.EncodeDecode

- Svc/LibaomAv1SvcTest.EncodeAndDecodeAllDecodeTargets/L1T1

- Svc/LibaomAv1SvcTest.EncodeAndDecodeAllDecodeTargets/L1T2

- Svc/LibaomAv1SvcTest.EncodeAndDecodeAllDecodeTargets/L1T3

- ...13 more failure(s) (17 total)...

---
* [webrtc/try/linux_x86_rel](https://cr-buildbucket.appspot.com/build/8757288114135768993). Summary [(view all results)](https://webrtc-review.googlesource.com/c/337283?checksPatchset=1&tab=checks):

---
1 Test Suite(s) failed.

**modules_unittests** failed because of:

- LibaomAv1Test.EncodeDecode

- Svc/LibaomAv1SvcTest.EncodeAndDecodeAllDecodeTargets/L1T1

- Svc/LibaomAv1SvcTest.EncodeAndDecodeAllDecodeTargets/L1T2

- Svc/LibaomAv1SvcTest.EncodeAndDecodeAllDecodeTargets/L1T3

- ...13 more failure(s) (17 total)...

---
* [webrtc/try/mac_rel_m1](https://cr-buildbucket.appspot.com/build/8757287743749117121). Summary [(view all results)](https://webrtc-review.googlesource.com/c/337283?checksPatchset=1&tab=checks):

---
1 Test Suite(s) failed.

**modules_unittests** failed because of:

- LibaomAv1Test.EncodeDecode

- Svc/LibaomAv1SvcTest.EncodeAndDecodeAllDecodeTargets/L1T1

- Svc/LibaomAv1SvcTest.EncodeAndDecodeAllDecodeTargets/L1T2

- Svc/LibaomAv1SvcTest.EncodeAndDecodeAllDecodeTargets/L1T3

- ...13 more failure(s) (17 total)...

---

Patch-set: 1
Tag: autogenerated:cq:full-run:1706796080