Create patch set 3
Change has been successfully rebased and submitted as aaaeb29ef54828cce3f6aab4d718487640235ab5

1 is the latest approved patch-set.
The change was submitted with unreviewed changes in the following files:

```
The name of the file: g3doc/abseil-in-webrtc.md
Insertions: 2, Deletions: 1.

@@ -81,4 +81,5 @@
 to the binary.
 
 Exception: Single-argument absl::StrCat is allowed in order to make it
-easy to use absl::Stringify.
+easy to use AbslStringify. See [TOTW #2015](https://abseil.io/tips/215) for
+details on AbslStringify.
```


Patch-set: 3
Patch-set-description: Rebase
Subject: Allow single-argument StrCat
Status: merged
Commit: aaaeb29ef54828cce3f6aab4d718487640235ab5
Tag: autogenerated:gerrit:merged
Groups: 9dac3567014d96dbe698298db55439fb7ef1c5d6
Label: Code-Review=+1, 1aab0bee4cad3ac7dcdbf2b17a9bd77dc1765c8c Gerrit User 5019 <5019@58829da1-049c-39fb-b951-ebdcd0984767>
Label: Commit-Queue=+2, 85c58d895ceac451f86bba8202ffc83ff4987d9d Gerrit User 5634 <5634@58829da1-049c-39fb-b951-ebdcd0984767>
Label: SUBM=+1, 5cde965769ce00d3bcbdf3b0b73e317069c2d592
Submission-id: 367204
Submitted-with: OK
Submitted-with: Rule-Name: gerrit~DefaultSubmitRule
Submitted-with: MAY: Auto-Submit
Submitted-with: MAY: Bot-Commit
Submitted-with: MAY: Code-Review: Gerrit User 5019 <5019@58829da1-049c-39fb-b951-ebdcd0984767>
Submitted-with: MAY: Owners-Override
Submitted-with: MAY: Commit-Queue: Gerrit User 5634 <5634@58829da1-049c-39fb-b951-ebdcd0984767>
Submitted-with: OK
Submitted-with: Rule-Name: Code-Owners
Attention: {"person_ident":"Gerrit User 5087 \u003c5087@58829da1-049c-39fb-b951-ebdcd0984767\u003e","operation":"REMOVE","reason":"Change was submitted"}