Update patch set 1
Patch Set 1:

Failed builds:
  luci.webrtc.try/android_arm_rel JOB_FAILED https://cr-buildbucket.appspot.com/build/8850844676235717024
    #### Step _generate_build_files_ failed. Error logs are shown below:
    ```
    ERROR at //build/config/android/rules.gni:3923:29: Assignment had no effect.
          enable_native_mocks = true
                                ^---
    You set the variable "enable_native_mocks" here and it was unused before it went
    out of scope.
    See //build/config/android/rules.gni:3918:5: whence it was called.
        android_apk(target_name) {
        ^-------------------------
    See //testing/test.gni:185:7: whence it was called.
          unittest_apk(_apk_target) {
          ^--------------------------
    See //webrtc.gni:443:3: whence it was called.
      test(target_name) {
      ^------------------
    See //BUILD.gn:532:3: whence it was called.
      rtc_test("rtc_unittests") {
      ^--------------------------
    ```
    #### More information can be found in the stdout.
  luci.webrtc.try/android_arm64_rel JOB_FAILED https://cr-buildbucket.appspot.com/build/8850844676235717072
    #### Step _generate_build_files_ failed. Error logs are shown below:
    ```
    ERROR at //build/config/android/rules.gni:3923:29: Assignment had no effect.
          enable_native_mocks = true
                                ^---
    You set the variable "enable_native_mocks" here and it was unused before it went
    out of scope.
    See //build/config/android/rules.gni:3918:5: whence it was called.
        android_apk(target_name) {
        ^-------------------------
    See //testing/test.gni:185:7: whence it was called.
          unittest_apk(_apk_target) {
          ^--------------------------
    See //webrtc.gni:443:3: whence it was called.
      test(target_name) {
      ^------------------
    See //BUILD.gn:532:3: whence it was called.
      rtc_test("rtc_unittests") {
      ^--------------------------
    ```
    #### More information can be found in the stdout.
  luci.webrtc.try/ios_compile_arm64_dbg JOB_FAILED https://cr-buildbucket.appspot.com/build/8850844676235716912
    recipe infra failure: Infra compile failure: #### Step _compile_ failed. Error logs are shown below:
    ```
    [88/1967] CXX obj/net/dcsctp/common/dcsctp_common_unittests/str_join_test.o
    FAILED: obj/net/dcsctp/common/dcsctp_common_unittests/str_join_test.o
    /opt/s/w/ir/cache/goma/client/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -...(too long)
    GOMA:clang++ compiling ../../net/dcsctp/common/str_join_test.cc:*ERROR*: compiler_proxy [579.013551ms]: open for write error:/opt/s/w/ir/cache/builder/src/out/Debug-iphoneos/obj/net/dcsctp/common/dcsctp_common_unittests/str_join_test.o
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output[failure_summary]
  luci.webrtc.try/android_compile_x64_dbg JOB_FAILED https://cr-buildbucket.appspot.com/build/8850844676235716960
    #### Step _generate_build_files_ failed. Error logs are shown below:
    ```
    ERROR at //build/config/android/rules.gni:3923:29: Assignment had no effect.
          enable_native_mocks = true
                                ^---
    You set the variable "enable_native_mocks" here and it was unused before it went
    out of scope.
    See //build/config/android/rules.gni:3918:5: whence it was called.
        android_apk(target_name) {
        ^-------------------------
    See //testing/test.gni:185:7: whence it was called.
          unittest_apk(_apk_target) {
          ^--------------------------
    See //webrtc.gni:443:3: whence it was called.
      test(target_name) {
      ^------------------
    See //BUILD.gn:532:3: whence it was called.
      rtc_test("rtc_unittests") {
      ^--------------------------
    ```
    #### More information can be found in the stdout.
  luci.webrtc.try/mac_compile_dbg JOB_FAILED https://cr-buildbucket.appspot.com/build/8850844676235716528
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [293/1056] CXX obj/common_video/common_video_unittests/libyuv_unittest.o
    FAILED: obj/common_video/common_video_unittests/libyuv_unittest.o
    /opt/s/w/ir/cache/goma/client/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -...(too long)
    In file included from ../../common_video/libyuv/libyuv_unittest.cc:11:
    In file included from ../../third_party/libyuv/include/libyuv.h:25:
    ../../third_party/libyuv/include/libyuv/row.h:750:5: error: 'LIBYUV_UNLIMITED_DATA' is not defined, evaluates to 0 [-Werror,-Wundef]
    #if LIBYUV_UNLIMITED_DATA
    ^
    1 error generated.
    [329/1056] CXX obj/common_video/common_video/webrtc_libyuv.o
    FAILED: obj/common_video/common_video/webrtc_libyuv.o
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output[failure_summary]

Patch-set: 1
Tag: autogenerated:cq:full-run