Update patch set 5
Patch Set 5:

Failed builds:
  luci.webrtc.try/ios_compile_arm64_dbg JOB_FAILED https://cr-buildbucket.appspot.com/build/8837394870719162865
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [5471/5754] CXX obj/rtc_base/rtc_base_approved_unittests/bitstream_reader_unittest.o
    FAILED: obj/rtc_base/rtc_base_approved_unittests/bitstream_reader_unittest.o
    /opt/s/w/ir/cache/goma/client/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -...(too long)
    ../../rtc_base/bitstream_reader_unittest.cc:34:3: error: use of undeclared identifier 'EXPECT_DEATH'
    EXPECT_DEATH(reader = absl::nullopt, "");
    ^
    ../../rtc_base/bitstream_reader_unittest.cc:46:3: error: use of undeclared identifier 'EXPECT_DEATH'
    EXPECT_DEATH(reader = absl::nullopt, "");
    ^
    2 errors generated.
    ```
    #### More information in raw_io.output[failure_summary]
  luci.webrtc.try/win_x64_msvc_dbg JOB_FAILED https://cr-buildbucket.appspot.com/build/8837394870719162321
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [28/681] CXX obj/rtc_base/bitstream_reader/bitstream_reader.obj
    FAILED: obj/rtc_base/bitstream_reader/bitstream_reader.obj
    ninja -t msvc -e environment.x64 -- "C:\b\s\w\ir\cache\builder\src\third_party\depot_tools\win_toolc...(too long)
    ../../rtc_base/bitstream_reader.cc(119): error C2220: the following warning is treated as an error
    ../../rtc_base/bitstream_reader.cc(119): warning C4334: '<<': result of 32-bit shift implicitly converted to 64 bits (was 64-bit shift intended?)
    ```
    #### More information in raw_io.output[failure_summary]

Patch-set: 5
Tag: autogenerated:cv