Remove LegacyAudioDeviceModule.java
LegacyAudioDeviceModule depends on
org.webrtc.voiceengine.WebRtcAudioTrack and
org.webrtc.voiceengine.WebRtcAudioRecord, which were removed in
https://webrtc.googlesource.com/src/+/6fc700ec3d1f86d06e203011aa8f375f32b39d9e.

Including LegacyAudioDeviceModule results in build failures like:
> /builds/worker/checkouts/gecko/third_party/libwebrtc/sdk/android/api/org/webrtc/audio/LegacyAudioDeviceModule.java:13: error: package org.webrtc.voiceengine does not exist
> import org.webrtc.voiceengine.WebRtcAudioRecord;
>                              ^
> /builds/worker/checkouts/gecko/third_party/libwebrtc/sdk/android/api/org/webrtc/audio/LegacyAudioDeviceModule.java:14: error: package org.webrtc.voiceengine does not exist
> import org.webrtc.voiceengine.WebRtcAudioTrack;
>                              ^
> /builds/worker/checkouts/gecko/third_party/libwebrtc/sdk/android/api/org/webrtc/audio/LegacyAudioDeviceModule.java:39: error: non-static method setSpeakerMute(boolean) cannot be referenced from a static context
>     WebRtcAudioTrack.setSpeakerMute(mute);
>                     ^
> /builds/worker/checkouts/gecko/third_party/libwebrtc/sdk/android/api/org/webrtc/audio/LegacyAudioDeviceModule.java:44: error: non-static method setMicrophoneMute(boolean) cannot be referenced from a static context
>     WebRtcAudioRecord.setMicrophoneMute(mute);

Bug: webrtc:7452
Change-Id: Icaa4447ec6dc274d89f827ce4d1cc13c3e9f55ad