Update patch set 7
Patch Set 7: Code-Review+1 Commit-Queue+2

> Patch Set 7:
> 
> > Patch Set 7:
> > 
> > After updating my branch with latest master I am having trouble running the android_instrumentation_test_apk target. I see the following stack trace. Any idea how to resolve this issue?
> > 
> > ./out/Debug/bin/run_android_instrumentation_test_apk
> > ninja: Entering directory `out/Debug'
> > [4238/4238] STAMP obj/sdk/android/android_instrumentation_test_apk.stamp
> > W    0.016s Main  Unable to find package info for org.webrtc
> > E    0.019s Main  Unrecognized error occurred.
> > Traceback (most recent call last):
> >   File "build/android/test_runner.py", line 990, in main
> >     return RunTestsCommand(args)
> >   File "build/android/test_runner.py", line 677, in RunTestsCommand
> >     return RunTestsInPlatformMode(args)
> >   File "build/android/test_runner.py", line 799, in RunTestsInPlatformMode
> >     test_run = test_run_factory.CreateTestRun(env, test_instance, infra_error)
> >   File "/home/vagrant/development/twilio/webrtc-build/src/build/android/pylib/base/test_run_factory.py", line 26, in CreateTestRun
> >     .LocalDeviceInstrumentationTestRun(env, test_instance))
> >   File "/home/vagrant/development/twilio/webrtc-build/src/build/android/pylib/local/device/local_device_instrumentation_test_run.py", line 132, in __init__
> >     env, test_instance)
> >   File "/home/vagrant/development/twilio/webrtc-build/src/build/android/pylib/local/device/local_device_test_run.py", line 55, in __init__
> >     env.SetPreferredAbis(test_instance.GetPreferredAbis())
> >   File "/home/vagrant/development/twilio/webrtc-build/src/build/android/pylib/instrumentation/instrumentation_test_instance.py", line 859, in GetPreferredAbis
> >     ret = apk.GetAbis()
> >   File "/home/vagrant/development/twilio/webrtc-build/src/third_party/catapult/devil/devil/android/apk_helper.py", line 389, in GetAbis
> >     for path in self._ListApkPaths():
> >   File "/home/vagrant/development/twilio/webrtc-build/src/third_party/catapult/devil/devil/android/apk_helper.py", line 382, in _ListApkPaths
> >     with zipfile.ZipFile(base_apk_path) as z:
> >   File "/usr/lib/python2.7/zipfile.py", line 770, in __init__
> >     self._RealGetContents()
> >   File "/usr/lib/python2.7/zipfile.py", line 857, in _RealGetContents
> >     x._decodeExtra()
> >   File "/usr/lib/python2.7/zipfile.py", line 388, in _decodeExtra
> >     tp, ln = unpack('<HH', extra[:4])
> 
> I left out the final line of the stack trace.
> 
> error: unpack requires a string argument of length 4

Sorry, I haven't seen this. To me it looks like it might be a bug with the version of zipfile python
module installed on your computer.

The test passes on the bot so it should be fine.

Patch-set: 7
Reviewer: Gerrit User 5112 <5112@58829da1-049c-39fb-b951-ebdcd0984767>
Label: Code-Review=+1
Label: Commit-Queue=+2