Update patch set 1
Patch Set 1:

Failed builds:
  luci.webrtc.try/ios_compile_arm_dbg JOB_FAILED https://cr-buildbucket.appspot.com/build/8849395152673395536
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [1180/5894] OBJC obj/examples/socketrocket/SRWebSocket.o
    FAILED: obj/examples/socketrocket/SRWebSocket.o
    /opt/s/w/ir/cache/goma/client/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang -MMD -MF...(too long)
    ../../examples/objc/AppRTCMobile/third_party/SocketRocket/SRWebSocket.m:1490:42: error: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior [-Werror,-Wimplicit-retain-self]
    [self _failWithError:_inputStream.streamError];
    ^
    self->
    1 error generated.
    ```
    #### More information in raw_io.output[failure_summary]
  luci.webrtc.try/ios_compile_arm_rel JOB_FAILED https://cr-buildbucket.appspot.com/build/8849395152673395520
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [1083/5480] OBJC obj/examples/socketrocket/SRWebSocket.o
    FAILED: obj/examples/socketrocket/SRWebSocket.o
    /opt/s/w/ir/cache/goma/client/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang -MMD -MF...(too long)
    ../../examples/objc/AppRTCMobile/third_party/SocketRocket/SRWebSocket.m:1490:42: error: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior [-Werror,-Wimplicit-retain-self]
    [self _failWithError:_inputStream.streamError];
    ^
    self->
    1 error generated.
    ```
    #### More information in raw_io.output[failure_summary]
  luci.webrtc.try/android_arm_rel JOB_FAILED https://cr-buildbucket.appspot.com/build/8849395152673395680
    #### Step _generate_build_files_ failed. Error logs are shown below:
    ```
    ERROR at //base/BUILD.gn:3348:34: Assignment had no effect.
          add_unwind_tables_in_apk = true
                                     ^---
    You set the variable "add_unwind_tables_in_apk" here and it was unused before it went
    out of scope.
    See //testing/test.gni:118:7: whence it was called.
          executable(_exec_target) {
          ^-------------------------
    See //base/BUILD.gn:2867:1: whence it was called.
    test("base_unittests") {
    ^-----------------------
    See //build/config/android/internal_rules.gni:2301:20: which caused the file to be included.
            _deps += [ "${_target_label}__assetres" ]
                       ^---------------------------
    ```
    #### More information can be found in the stdout.
  luci.webrtc.try/linux_compile_arm_rel JOB_FAILED https://cr-buildbucket.appspot.com/build/8849395152673395408
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [108/2773] CXX obj/base/base/file_path.o
    FAILED: obj/base/base/file_path.o
    /b/s/w/ir/cache/goma/client/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF...(too long)
    ../../base/files/file_path.cc:1365:13: error: no member named 'WriteIntoTracedValue' in namespace 'perfetto'; did you mean 'WriteIntoTrace'?
    perfetto::WriteIntoTracedValue(std::move(context), value());
    ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
    WriteIntoTrace
    ../../base/trace_event/trace_event_stub.h:246:6: note: 'WriteIntoTrace' declared here
    void WriteIntoTrace(TracedValue, T&&) {}
    ^
    1 error generated.
    ```
    #### More information in raw_io.output[failure_summary]
  luci.webrtc.try/linux_compile_dbg JOB_FAILED https://cr-buildbucket.appspot.com/build/8849395152673395392
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [1604/6315] CXX obj/base/base/file_path.o
    FAILED: obj/base/base/file_path.o
    /b/s/w/ir/cache/goma/client/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF...(too long)
    ../../base/files/file_path.cc:1365:13: error: no member named 'WriteIntoTracedValue' in namespace 'perfetto'; did you mean 'WriteIntoTrace'?
    perfetto::WriteIntoTracedValue(std::move(context), value());
    ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
    WriteIntoTrace
    ../../base/trace_event/trace_event_stub.h:246:6: note: 'WriteIntoTrace' declared here
    void WriteIntoTrace(TracedValue, T&&) {}
    ^
    1 error generated.
    ```
    #### More information in raw_io.output[failure_summary]
  luci.webrtc.try/linux_x86_dbg JOB_FAILED https://cr-buildbucket.appspot.com/build/8849395152673395248
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [547/3536] CXX obj/base/base/file_path.o
    FAILED: obj/base/base/file_path.o
    /b/s/w/ir/cache/goma/client/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF...(too long)
    ../../base/files/file_path.cc:1365:13: error: no member named 'WriteIntoTracedValue' in namespace 'perfetto'; did you mean 'WriteIntoTrace'?
    perfetto::WriteIntoTracedValue(std::move(context), value());
    ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
    WriteIntoTrace
    ../../base/trace_event/trace_event_stub.h:246:6: note: 'WriteIntoTrace' declared here
    void WriteIntoTrace(TracedValue, T&&) {}
    ^
    1 error generated.
    ```
    #### More information in raw_io.output[failure_summary]
  luci.webrtc.try/linux_x86_rel JOB_FAILED https://cr-buildbucket.appspot.com/build/8849395152673395232
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [483/4007] CXX obj/base/base/file_path.o
    FAILED: obj/base/base/file_path.o
    /b/s/w/ir/cache/goma/client/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF...(too long)
    ../../base/files/file_path.cc:1365:13: error: no member named 'WriteIntoTracedValue' in namespace 'perfetto'; did you mean 'WriteIntoTrace'?
    perfetto::WriteIntoTracedValue(std::move(context), value());
    ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
    WriteIntoTrace
    ../../base/trace_event/trace_event_stub.h:246:6: note: 'WriteIntoTrace' declared here
    void WriteIntoTrace(TracedValue, T&&) {}
    ^
    1 error generated.
    ```
    #### More information in raw_io.output[failure_summary]

Patch-set: 1
Tag: autogenerated:cq:full-run