Update patch set 8
Patch Set 8:

Try jobs failed on following builders:
  luci.webrtc.try/presubmit JOB_FAILED https://ci.chromium.org/b/8906238606035138528
    There are 2 error(s), 0 warning(s), and 11 notifications(s). Here are the errors:
    
    **ERROR**
    
    You need LGTM from owners of depends-on paths in DEPS that were modified in this CL:
    
        '+p2p',
    
        '+pc',
    
    
    
    **ERROR**
    
    Suggested missing target path OWNERS:
    
        juberti@webrtc.org
    
    
    
    To see notifications and warnings, look at the stdout of the presubmit step.
  luci.webrtc.try/android_compile_arm_rel JOB_FAILED https://ci.chromium.org/b/8906238606035138448
    **Compile failure**
    
    List of errors:
    
    - ```../../test/peer_scenario/peer_scenario.cc:39:30: error: no member named 'ep' in 'webrtc::test::PeerScenarioClient'```
    
    - ```../../test/peer_scenario/peer_scenario.cc:39:55: error: no member named 'ep' in 'webrtc::test::PeerScenarioClient'```
    
    - ```../../test/peer_scenario/peer_scenario.cc:40:30: error: no member named 'ep' in 'webrtc::test::PeerScenarioClient'```
    
    - ```../../test/peer_scenario/peer_scenario.cc:40:54: error: no member named 'ep' in 'webrtc::test::PeerScenarioClient'```
    
    - ```../../test/peer_scenario/peer_scenario_client.cc:186:39: error: out-of-line definition of 'ep' does not match any declaration in 'webrtc::test::PeerScenarioClient'```
  luci.webrtc.try/linux_compile_arm64_rel JOB_FAILED https://ci.chromium.org/b/8906238606035138128
    **Compile failure**
    
    List of errors:
    
    - ```../../test/peer_scenario/peer_scenario_client.cc:186:39: error: out-of-line definition of 'ep' does not match any declaration in 'webrtc::test::PeerScenarioClient'```
    
    - ```../../test/peer_scenario/peer_scenario.cc:39:30: error: no member named 'ep' in 'webrtc::test::PeerScenarioClient'```
    
    - ```../../test/peer_scenario/peer_scenario.cc:39:55: error: no member named 'ep' in 'webrtc::test::PeerScenarioClient'```
    
    - ```../../test/peer_scenario/peer_scenario.cc:40:30: error: no member named 'ep' in 'webrtc::test::PeerScenarioClient'```
    
    - ```../../test/peer_scenario/peer_scenario.cc:40:54: error: no member named 'ep' in 'webrtc::test::PeerScenarioClient'```

Patch-set: 8
Tag: autogenerated:cq:full-run