Revert "sctp: Add DcsctpTransport based on dcSCTP"
This reverts commit a6983c6ea20fdae57945e8aeab45bb99d7e7b23d.

Reason for revert: Causes build failure on iOS builder bot.

First failure:
https://ci.chromium.org/p/webrtc/builders/ci/iOS%20API%20Framework%20Builder/19512?

Build errors:
../../net/dcsctp/rx/reassembly_queue.cc:205:27: error: loop variable 'tsn' of type 'const dcsctp::UnwrappedTSN' (aka 'const UnwrappedSequenceNumber<StrongAlias<dcsctp::TSNTag, unsigned int> >') creates a copy from type 'const dcsctp::UnwrappedTSN' [-Werror,-Wrange-loop-analysis]
  for (const UnwrappedTSN tsn : tsns) {
                          ^
../../net/dcsctp/rx/reassembly_queue.cc:205:8: note: use reference type 'const dcsctp::UnwrappedTSN &' (aka 'const UnwrappedSequenceNumber<StrongAlias<dcsctp::TSNTag, unsigned int> > &') to prevent copying
  for (const UnwrappedTSN tsn : tsns) {
       ^~~~~~~~~~~~~~~~~~~~~~~~
                          &

Original change's description:
> sctp: Add DcsctpTransport based on dcSCTP
>
> Bug: webrtc:12614
> Change-Id: Ie710621610fff9f8bb6c7d800419675892d6a70c
> Reviewed-on: https://webrtc-review.googlesource.com/c/src/+/215680
> Commit-Queue: Florent Castelli <orphis@webrtc.org>
> Reviewed-by: Harald Alvestrand <hta@webrtc.org>
> Reviewed-by: Victor Boivie <boivie@webrtc.org>
> Cr-Commit-Position: refs/heads/master@{#33935}

# Not skipping CQ checks because original CL landed > 1 day ago.

Bug: webrtc:12614
TBR: orphis@webrtc.org
Change-Id: I0cbd7f60646ebea51fd1e5000822f5e1a5f7c8fa