Update patch set 2
Patch Set 2:

Dry run: Failed builds:
  luci.webrtc.try/win_x86_msvc_rel JOB_FAILED https://cr-buildbucket.appspot.com/build/8836826331546803937
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [3/152] CXX obj/modules/audio_processing/agc/agc_unittests/clipping_predictor_evaluator_unittest.obj
    FAILED: obj/modules/audio_processing/agc/agc_unittests/clipping_predictor_evaluator_unittest.obj
    ninja -t msvc -e environment.x86 -- "C:\b\s\w\ir\cache\builder\src\third_party\depot_tools\win_toolc...(too long)
    ../../modules/audio_processing/agc/clipping_predictor_evaluator_unittest.cc(579): error C7555: use of designated initializers requires at least '/std:c++latest'
    ../../modules/audio_processing/agc/clipping_predictor_evaluator_unittest.cc(585): error C7555: use of designated initializers requires at least '/std:c++latest'
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output[failure_summary]

Patch-set: 2
Tag: autogenerated:cv