Update patch set 5
Patch Set 5:

(1 comment)

That's still WIP, but I need some help of the JAVA part:

With this roll, errorprone start complaining:

./../sdk/android/src/java/org/webrtc/WebRtcClassLoader.java:21: error: [ReturnMissingNullable] May return null
    return WebRtcClassLoader.class.getClassLoader();
    ^
    (see http://errorprone.info/bugpattern/ReturnMissingNullable)
  Did you mean '@Nullable @CalledByNative'?

I'm not sure of the proper fix: Annotate, or fix the function so it cannot return null?
I don't know how the annotation work (see comment).

Patch-set: 5
Reviewer: Gerrit User 5112 <5112@58829da1-049c-39fb-b951-ebdcd0984767>
CC: Gerrit User 7332 <7332@58829da1-049c-39fb-b951-ebdcd0984767>
Work-in-progress: false