Revert "Add option to call VMAF in compare_videos.py."
This reverts commit e307d56bd7e192c354871a739bc0133d88cb5379.

Reason for revert:
Breaks client.webrtc.perf bots. Example failure:
https://ci.chromium.org/buildbot/client.webrtc.perf/Android32%20Tests%20(L%20Nexus7.2)/8635

AttributeError: Values instance has no attribute 'yuv_directory'

Original change's description:
> Add option to call VMAF in compare_videos.py.
> 
> VMAF compares videos on several metrics and produces a unified score.
> 
> Calling it from compare_videos required passing in a path to a VMAF
> directory, where there should be a C++ wrapper executable and a model.
> For now, the relative paths to those are constant.
> 
> VMAF needs to compare aligned videos in YUV format, so two videos
> (ref and test) will be saved by frame_analyzer after it has aligned
> them.
> 
> Bug: webrtc:9642
> Change-Id: Idddfcf6b1b235e7f925696ffc38938fb84c4ff9e
> Reviewed-on: https://webrtc-review.googlesource.com/102140
> Reviewed-by: Patrik Höglund <phoglund@webrtc.org>
> Reviewed-by: Sami Kalliomäki <sakal@webrtc.org>
> Commit-Queue: Paulina Hensman <phensman@webrtc.org>
> Cr-Commit-Position: refs/heads/master@{#24876}

TBR=phoglund@webrtc.org,sakal@webrtc.org,phensman@webrtc.org

Change-Id: I3e1dc98d7dfc0309ee2934cb3a978eecf274c477
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: webrtc:9642