Update patch set 4
Patch Set 4:

Dry run: Failed builds:
  luci.webrtc.try/win_x64_msvc_dbg JOB_FAILED https://cr-buildbucket.appspot.com/build/8850683629726379344
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [3891/4084] CXX obj/video/video/video_receive_stream2.obj
    FAILED: obj/video/video/video_receive_stream2.obj
    ninja -t msvc -e environment.x64 -- "C:\b\s\w\ir\cache\builder\src\third_party\depot_tools\win_toolc...(too long)
    ../../video/video_receive_stream2.cc(780): error C7555: use of designated initializers requires at least '/std:c++latest'
    ```
    #### More information in raw_io.output[failure_summary]

Patch-set: 4
Tag: autogenerated:cq:dry-run