Update patch set 3
Patch Set 3:

Dry run: Failed builds:
  luci.webrtc.try/win_x86_msvc_rel JOB_FAILED https://cr-buildbucket.appspot.com/build/8835860669484419089
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [304/698] CXX obj/rtc_base/rtc_base_approved_unittests/copy_on_write_buffer_unittest.obj
    FAILED: obj/rtc_base/rtc_base_approved_unittests/copy_on_write_buffer_unittest.obj
    ninja -t msvc -e environment.x86 -- "C:\b\s\w\ir\cache\builder\src\third_party\depot_tools\win_toolc...(too long)
    C:\b\s\w\ir\cache\builder\src\third_party\depot_tools\win_toolchain\vs_files\3bda71a11e\VC\Tools\MSVC\14.26.28801\include\xmemory(740): error C2338: The C++ Standard forbids containers of const elements because allocator<const T> is ill-formed.
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output[failure_summary]
  luci.webrtc-internal.g3.webrtc-internal.try/internal_compile_lite JOB_FAILED https://cr-buildbucket.appspot.com/build/8835860669484419889

Patch-set: 3
Tag: autogenerated:cv