Update patch set 2
Patch Set 2:

Dry run: Try jobs failed on following builders:
  luci.webrtc.try/win_x64_msvc_dbg JOB_FAILED https://ci.chromium.org/b/8890567138136481168
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [223/500] CXX obj/modules/rtp_rtcp/rtp_rtcp_unittests/rtp_sender_video_unittest.obj
    FAILED: obj/modules/rtp_rtcp/rtp_rtcp_unittests/rtp_sender_video_unittest.obj
    ninja -t msvc -e environment.x64 -- "C:\b\s\w\ir\cache\builder\src\third_party\depot_tools\win_toolc...(too long)
    ../../modules/rtp_rtcp/source/rtp_sender_video_unittest.cc(637): error C3493: 'kAbsoluteCaptureTimestampMs' cannot be implicitly captured because no default capture mode has been specified
    ```
    #### More information in raw_io.output[failure_summary]

Patch-set: 2
Tag: autogenerated:cq:dry-run