Update patch set 1
Patch Set 1:

PTAL.

This seems to break something nacl-related. Not sure why. The new target depends on rtc_base, and that target includes some if (is_nacl) config. Breakage is

[1811/13784] CXX newlib_pnacl/obj/third_party/webrtc/rtc_base/fifo_buffer/fifo_buffer.o
FAILED: newlib_pnacl/obj/third_party/webrtc/rtc_base/fifo_buffer/fifo_buffer.o 
/b/s/w/ir/cache/goma/client/gomacc ../../native_client/toolchain/mac_x86/pnacl_newlib/bin/pnacl-clang++ -MMD -MF newlib_pnacl/obj/third_party/webrtc/rtc_base/fifo_buffer/fifo_buffer.o.d -DNACL_TC_REV=15362ac60573769f6606ab1d1c11668052e411a7 -DDCHECK_ALWAYS_ON=1 -DNO_TCMALLOC -DFULL_SAFE_BROWSING -DSAFE_BROWSING_CSD -DSAFE_BROWSING_DB_LOCAL -DCHROMIUM_BUILD -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_GNU_SOURCE -DCR_CLANG_REVISION=\"356356-1\" -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FORTIFY_SOURCE=2 -DNDEBUG -DNVALGRIND -DWEBRTC_ENABLE_PROTOBUF=1 -DRTC_ENABLE_VP9 -DHAVE_SCTP -DENABLE_EXTERNAL_AUTH -DWEBRTC_USE_H264 -DHAVE_WEBRTC_VIDEO -DLOGGING_INSIDE_WEBRTC -DWEBRTC_LIBRARY_IMPL -DWEBRTC_NON_STATIC_TRACE_EVENT_HANDLERS=0 -DWEBRTC_CHROMIUM_BUILD -DWEBRTC_POSIX -DABSL_ALLOCATOR_NOTHROW=1 -DNO_MAIN_THREAD_WRAPPING -I../.. -Inewlib_pnacl/gen -I../../third_party/webrtc_overrides -I../../third_party/webrtc -Inewlib_pnacl/gen/third_party/webrtc -I../../third_party/abseil-cpp -fno-strict-aliasing -fcolor-diagnostics -fmerge-all-constants -U__STRICT_ANSI__ -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -Xclang -fdebug-compilation-dir -Xclang . -Wall -Werror -Wextra -Wimplicit-fallthrough -Wthread-safety -Wextra-semi -Wno-missing-field-initializers -Wno-unused-parameter -Wno-c++11-narrowing -Wno-unneeded-internal-declaration -O2 -fno-ident -fdata-sections -ffunction-sections -fomit-frame-pointer -g1 -fvisibility=hidden -Wexit-time-destructors -Wglobal-constructors -std=c++14 -fno-exceptions -fno-rtti -fvisibility-inlines-hidden -c ../../third_party/webrtc/rtc_base/fifo_buffer.cc -o newlib_pnacl/obj/third_party/webrtc/rtc_base/fifo_buffer/fifo_buffer.o
In file included from ../../third_party/webrtc/rtc_base/fifo_buffer.cc:11:
In file included from ../../third_party/webrtc/rtc_base/fifo_buffer.h:16:
In file included from ../../third_party/webrtc/rtc_base/stream.h:22:
In file included from ../../third_party/webrtc/rtc_base/message_queue.h:27:
In file included from ../../third_party/webrtc/rtc_base/socket_server.h:15:
In file included from ../../third_party/webrtc/rtc_base/socket_factory.h:14:
In file included from ../../third_party/webrtc/rtc_base/async_socket.h:17:
../../third_party/webrtc/rtc_base/socket.h:17:10: fatal error: 'arpa/inet.h' file not found
#include <arpa/inet.h>
         ^
1 error generated.

and that include is protected by an #if defined(WEBRTC_POSIX)

Patch-set: 1
Reviewer: Gerrit User 5087 <5087@58829da1-049c-39fb-b951-ebdcd0984767>
Reviewer: Gerrit User 5234 <5234@58829da1-049c-39fb-b951-ebdcd0984767>
Label: Commit-Queue=0
Work-in-progress: false