Update patch set 10
Patch Set 10:

Dry run: Failed builds:
  luci.webrtc.try/ios_compile_arm64_rel JOB_FAILED https://cr-buildbucket.appspot.com/build/8820061603102185457
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [793/797] SOLINK libgrpc++.dylib libgrpc++.dylib.TOC
    FAILED: libgrpc++.dylib libgrpc++.dylib.TOC
    if [ ! -e "./libgrpc++.dylib" -o ! -e "./libgrpc++.dylib.TOC" ] || sdk/xcode_links/XcodeDefault.xcto...(too long)
    ld64.lld: error: unknown argument '--version-script=../../third_party/grpc/grpc_shared_lib.map'
    clang++: error: linker command failed with exit code 1 (use -v to see invocation)
    Traceback (most recent call last):
    File "../../build/toolchain/apple/linker_driver.py", line 387, in <module>
    LinkerDriver(sys.argv).run()
    File "../../build/toolchain/apple/linker_driver.py", line 129, in run
    subprocess.check_call(compiler_driver_args, env=env)
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output_text[failure_summary]
  luci.webrtc.try/android_arm_dbg JOB_FAILED https://cr-buildbucket.appspot.com/build/8820061603102185633
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [5/773] CXX obj/third_party/grpc/grpc++_cc/grpc_ares_wrapper_posix.o
    FAILED: obj/third_party/grpc/grpc++_cc/grpc_ares_wrapper_posix.o
    /b/s/w/ir/cache/goma/client/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF...(too long)
    In file included from ../../third_party/grpc/src/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper_posix.cc:19:
    In file included from ../../third_party/grpc/src/include/grpc/support/port_platform.h:22:
    ../../third_party/grpc/src/include/grpc/impl/codegen/port_platform.h:135:2: error: "Requires Android API v21 and above"
    #error "Requires Android API v21 and above"
    ^
    1 error generated.
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output_text[failure_summary]
  luci.webrtc.try/android_compile_x86_rel JOB_FAILED https://cr-buildbucket.appspot.com/build/8820061603102185505
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [7/773] CXX obj/third_party/grpc/grpc++_cc/grpc_ares_wrapper_posix.o
    FAILED: obj/third_party/grpc/grpc++_cc/grpc_ares_wrapper_posix.o
    /b/s/w/ir/cache/goma/client/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF...(too long)
    In file included from ../../third_party/grpc/src/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper_posix.cc:19:
    In file included from ../../third_party/grpc/src/include/grpc/support/port_platform.h:22:
    ../../third_party/grpc/src/include/grpc/impl/codegen/port_platform.h:135:2: error: "Requires Android API v21 and above"
    #error "Requires Android API v21 and above"
    ^
    1 error generated.
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output_text[failure_summary]

Patch-set: 10
Tag: autogenerated:cq:dry-run
Attention: {"person_ident":"Gerrit User 7036 \u003c7036@58829da1-049c-39fb-b951-ebdcd0984767\u003e","operation":"ADD","reason":"ps#10: CQ dry run failed."}