Update patch set 1
Patch Set 1:

Failed builds:
  luci.webrtc.try/linux_msan JOB_FAILED https://cr-buildbucket.appspot.com/build/8851267474577475920
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [655/734] CXX obj/common_video/common_video/webrtc_libyuv.o
    FAILED: obj/common_video/common_video/webrtc_libyuv.o
    /b/s/w/ir/cache/goma/client/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF...(too long)
    In file included from ../../common_video/libyuv/webrtc_libyuv.cc:18:
    In file included from ../../third_party/libyuv/include/libyuv.h:25:
    ../../third_party/libyuv/include/libyuv/row.h:750:5: error: 'LIBYUV_UNLIMITED_DATA' is not defined, evaluates to 0 [-Werror,-Wundef]
    #if LIBYUV_UNLIMITED_DATA
    ^
    1 error generated.
    [656/734] CXX obj/modules/video_capture/video_capture_module/video_capture_impl.o
    FAILED: obj/modules/video_capture/video_capture_module/video_capture_impl.o
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output[failure_summary]
  luci.webrtc.try/linux_rel JOB_FAILED https://cr-buildbucket.appspot.com/build/8851267474577475904
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [536/865] CXX obj/modules/video_capture/video_capture_module/video_capture_impl.o
    FAILED: obj/modules/video_capture/video_capture_module/video_capture_impl.o
    /b/s/w/ir/cache/goma/client/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF...(too long)
    In file included from ../../modules/video_capture/video_capture_impl.cc:24:
    In file included from ../../third_party/libyuv/include/libyuv.h:25:
    ../../third_party/libyuv/include/libyuv/row.h:750:5: error: 'LIBYUV_UNLIMITED_DATA' is not defined, evaluates to 0 [-Werror,-Wundef]
    #if LIBYUV_UNLIMITED_DATA
    ^
    1 error generated.
    [537/865] CXX obj/common_video/common_video/webrtc_libyuv.o
    FAILED: obj/common_video/common_video/webrtc_libyuv.o
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output[failure_summary]
  luci.webrtc.try/linux_tsan2 JOB_FAILED https://cr-buildbucket.appspot.com/build/8851267474577475888
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [479/664] CXX obj/common_video/common_video/webrtc_libyuv.o
    FAILED: obj/common_video/common_video/webrtc_libyuv.o
    /b/s/w/ir/cache/goma/client/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF...(too long)
    In file included from ../../common_video/libyuv/webrtc_libyuv.cc:18:
    In file included from ../../third_party/libyuv/include/libyuv.h:25:
    ../../third_party/libyuv/include/libyuv/row.h:750:5: error: 'LIBYUV_UNLIMITED_DATA' is not defined, evaluates to 0 [-Werror,-Wundef]
    #if LIBYUV_UNLIMITED_DATA
    ^
    1 error generated.
    [500/664] CXX obj/modules/video_capture/video_capture_module/video_capture_impl.o
    FAILED: obj/modules/video_capture/video_capture_module/video_capture_impl.o
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output[failure_summary]
  luci.webrtc.try/android_compile_x64_dbg JOB_FAILED https://cr-buildbucket.appspot.com/build/8851267474577476208
    #### Step _generate_build_files_ failed. Error logs are shown below:
    ```
    ERROR at //build/config/android/rules.gni:3923:29: Assignment had no effect.
          enable_native_mocks = true
                                ^---
    You set the variable "enable_native_mocks" here and it was unused before it went
    out of scope.
    See //build/config/android/rules.gni:3918:5: whence it was called.
        android_apk(target_name) {
        ^-------------------------
    See //testing/test.gni:185:7: whence it was called.
          unittest_apk(_apk_target) {
          ^--------------------------
    See //webrtc.gni:443:3: whence it was called.
      test(target_name) {
      ^------------------
    See //BUILD.gn:531:3: whence it was called.
      rtc_test("rtc_unittests") {
      ^--------------------------
    ```
    #### More information can be found in the stdout.
  luci.webrtc.try/android_compile_arm64_rel JOB_FAILED https://cr-buildbucket.appspot.com/build/8851267474577476240
    #### Step _generate_build_files_ failed. Error logs are shown below:
    ```
    ERROR at //build/config/android/rules.gni:3923:29: Assignment had no effect.
          enable_native_mocks = true
                                ^---
    You set the variable "enable_native_mocks" here and it was unused before it went
    out of scope.
    See //build/config/android/rules.gni:3918:5: whence it was called.
        android_apk(target_name) {
        ^-------------------------
    See //testing/test.gni:185:7: whence it was called.
          unittest_apk(_apk_target) {
          ^--------------------------
    See //webrtc.gni:443:3: whence it was called.
      test(target_name) {
      ^------------------
    See //BUILD.gn:531:3: whence it was called.
      rtc_test("rtc_unittests") {
      ^--------------------------
    ```
    #### More information can be found in the stdout.

Patch-set: 1
Tag: autogenerated:cq:full-run