Update patch set 6
Patch Set 6:

Dry run: Failed builds:
  luci.webrtc.try/win_x86_msvc_dbg JOB_FAILED https://cr-buildbucket.appspot.com/build/8845736673933149952
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [2/407] CXX obj/modules/audio_processing/agc/clipping_predictor_level_buffer/clipping_predictor_level_buffer.obj
    FAILED: obj/modules/audio_processing/agc/clipping_predictor_level_buffer/clipping_predictor_level_buffer.obj
    ninja -t msvc -e environment.x86 -- "C:\b\s\w\ir\cache\builder\src\third_party\depot_tools\win_toolc...(too long)
    ../../modules/audio_processing/agc/clipping_predictor_level_buffer.cc(75): error C7555: use of designated initializers requires at least '/std:c++latest'
    [9/407] CXX obj/modules/audio_processing/agc/agc_unittests/clipping_predictor_level_buffer_unittest.obj
    FAILED: obj/modules/audio_processing/agc/agc_unittests/clipping_predictor_level_buffer_unittest.obj
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output[failure_summary]
  luci.webrtc.try/win_x64_msvc_rel JOB_FAILED https://cr-buildbucket.appspot.com/build/8845736673933150000
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [3/407] CXX obj/modules/audio_processing/agc/clipping_predictor_level_buffer/clipping_predictor_level_buffer.obj
    FAILED: obj/modules/audio_processing/agc/clipping_predictor_level_buffer/clipping_predictor_level_buffer.obj
    ninja -t msvc -e environment.x64 -- "C:\b\s\w\ir\cache\builder\src\third_party\depot_tools\win_toolc...(too long)
    ../../modules/audio_processing/agc/clipping_predictor_level_buffer.cc(75): error C7555: use of designated initializers requires at least '/std:c++latest'
    [9/407] CXX obj/modules/audio_processing/agc/agc_unittests/clipping_predictor_level_buffer_unittest.obj
    FAILED: obj/modules/audio_processing/agc/agc_unittests/clipping_predictor_level_buffer_unittest.obj
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output[failure_summary]

Patch-set: 6
Tag: autogenerated:cq:dry-run