Update patch set 1
Patch Set 1:

Dry run: Failed builds:
  luci.webrtc.try/win_x64_msvc_rel JOB_FAILED https://cr-buildbucket.appspot.com/build/8847972503993131888
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [1/149] CXX obj/modules/rtp_rtcp/rtp_rtcp/absolute_capture_time_receiver.obj
    FAILED: obj/modules/rtp_rtcp/rtp_rtcp/absolute_capture_time_receiver.obj
    ninja -t msvc -e environment.x64 -- "C:\b\s\w\ir\cache\builder\src\third_party\depot_tools\win_toolc...(too long)
    ../../modules/rtp_rtcp/source/absolute_capture_time_receiver.cc(71): error C7555: use of designated initializers requires at least '/std:c++latest'
    ../../modules/rtp_rtcp/source/absolute_capture_time_receiver.cc(99): error C7555: use of designated initializers requires at least '/std:c++latest'
    [20/149] CXX obj/modules/rtp_rtcp/rtp_rtcp_unittests/absolute_capture_time_receiver_unittest.obj
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output[failure_summary]
  luci.webrtc.try/win_x64_msvc_dbg JOB_FAILED https://cr-buildbucket.appspot.com/build/8847972503993131904
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [6/141] CXX obj/modules/rtp_rtcp/rtp_rtcp/absolute_capture_time_receiver.obj
    FAILED: obj/modules/rtp_rtcp/rtp_rtcp/absolute_capture_time_receiver.obj
    ninja -t msvc -e environment.x64 -- "C:\b\s\w\ir\cache\builder\src\third_party\depot_tools\win_toolc...(too long)
    ../../modules/rtp_rtcp/source/absolute_capture_time_receiver.cc(71): error C7555: use of designated initializers requires at least '/std:c++latest'
    ../../modules/rtp_rtcp/source/absolute_capture_time_receiver.cc(99): error C7555: use of designated initializers requires at least '/std:c++latest'
    [27/141] CXX obj/modules/rtp_rtcp/rtp_rtcp_unittests/absolute_capture_time_receiver_unittest.obj
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output[failure_summary]

Patch-set: 1
Tag: autogenerated:cq:dry-run