Update patch set 1
Patch Set 1:

Dry run: Failed builds:
  luci.webrtc.try/win_x64_msvc_rel JOB_FAILED https://cr-buildbucket.appspot.com/build/8869108066981171536
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [1002/5162] CXX obj/rtc_base/function_unittest/function_unittest.obj
    FAILED: obj/rtc_base/function_unittest/function_unittest.obj
    ninja -t msvc -e environment.x64 -- "C:\b\s\w\ir\cache\builder\src\third_party\depot_tools\win_toolc...(too long)
    ../..\rtc_base/function.h(130): error C7555: use of designated initializers requires at least '/std:c++latest'
    ../../rtc_base/function_unittest.cc(37): note: see reference to function template instantiation 'webrtc::UntypedFunction webrtc::UntypedFunction::Create<int(int)>(Signature (__cdecl *))' being compiled
    with
    [
    Signature=int (int)
    ]
    ../..\rtc_base/function.h(108): error C7555: use of designated initializers requires at least '/std:c++latest'
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output[failure_summary]

Patch-set: 1
Tag: autogenerated:cq:dry-run