Update patch set 2
Patch Set 2: Code-Review+1

Right, at the moment the roll is failing because of:

Error: open /b/c/b/android_compile_x64_dbg/src/build/cipd/android/android.ensure: no such file or directory.

And "Android CIPD Ensure" will be removed with this CL.

Patch-set: 2
Reviewer: Gerrit User 5087 <5087@58829da1-049c-39fb-b951-ebdcd0984767>
Label: Code-Review=+1