Update patch set 3
Patch Set 3:

Dry run: Failed builds:
  luci.webrtc.try/win_x86_msvc_rel JOB_FAILED https://cr-buildbucket.appspot.com/build/8846079235211557520
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [750/2875] CXX obj/modules/audio_processing/agc/clipping_predictor_level_buffer/clipping_predictor_level_buffer.obj
    FAILED: obj/modules/audio_processing/agc/clipping_predictor_level_buffer/clipping_predictor_level_buffer.obj
    ninja -t msvc -e environment.x86 -- "C:\b\s\w\ir\cache\builder\src\third_party\depot_tools\win_toolc...(too long)
    ../../modules/audio_processing/agc/clipping_predictor_level_buffer.cc(71): error C7555: use of designated initializers requires at least '/std:c++latest'
    [800/2875] CXX obj/modules/audio_processing/agc/agc_unittests/clipping_predictor_level_buffer_unittest.obj
    FAILED: obj/modules/audio_processing/agc/agc_unittests/clipping_predictor_level_buffer_unittest.obj
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output[failure_summary]

Patch-set: 3
Tag: autogenerated:cq:dry-run