Fix generate_buildbot_json and switch to ios_runtime_cache_17_4.
When running it, even without changes at HEAD I got:

```
KeyError: 'ios_runtime_cache_17_0'
```

Bug: b/325441006
Change-Id: I7ea236ccc1f7439d7750208260b01d7636db4ae5