Update patch set 1
Patch Set 1:

Dry run: Failed builds:
  luci.webrtc.try/win_x64_msvc_dbg JOB_FAILED https://cr-buildbucket.appspot.com/build/8884489924695073824
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [827/5030] CXX obj/modules/audio_processing/test/py_quality_assessment/sound_level/sound_level.obj
    FAILED: obj/modules/audio_processing/test/py_quality_assessment/sound_level/sound_level.obj
    ninja -t msvc -e environment.x64 -- "C:\b\s\w\ir\cache\builder\src\third_party\depot_tools\win_toolc...(too long)
    ../../modules/audio_processing/test/py_quality_assessment/quality_assessment/sound_level.cc(103): error C3535: cannot deduce type for 'const auto *' from '_FwdIt'
    with
    [
    _FwdIt=std::_Array_iterator<int16_t,1440>
    ]
    ../../modules/audio_processing/test/py_quality_assessment/quality_assessment/sound_level.cc(103): error C2440: 'initializing': cannot convert from '_FwdIt' to 'const int *'
    with
    [
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output[failure_summary]

Patch-set: 1
Tag: autogenerated:cq:dry-run