Update patch set 1
Patch Set 1:

This CL has failed the run. Reason:

Failed Tryjobs:
* [webrtc/try/android_compile_x64_dbg](https://cr-buildbucket.appspot.com/build/8731920573171443121). Summary ([view all results](https://webrtc-review.googlesource.com/c/367865?checksPatchset=1&tab=checks)):

---
#### Step _generate_build_files_ failed. Error logs are shown below:
```
ERROR at //build/rust/rust_target.gni:220:3: Assertion failed.
  assert(!defined(invoker.cxx_bindings) || enable_rust_cxx,
  ^-----
cxx bindings are not supported when building rust targets outside the Chromium build.
See //build/rust/rust_static_library.gni:214:3: whence it was called.
  rust_target(_target_name) {
  ^--------------------------
See //base/test/BUILD.gn:42:1: whence it was called.
rust_static_library("test_rust_logger_consumer") {
^-------------------------------------------------
See //build/config/android/internal_rules.gni:171:21: which caused the file to be included.
          deps += [ "$_dep_label$build_config_target_suffix" ]
                    ^---------------------------------------
```
#### More information can be found in the stdout.

---
* [webrtc/try/mac_asan](https://cr-buildbucket.appspot.com/build/8731920573171442705). Summary ([view all results](https://webrtc-review.googlesource.com/c/367865?checksPatchset=1&tab=checks)):

---
#### Step _compile_ failed. Error logs are shown below:
```
[2646/5360] OBJC obj/examples/socketrocket/SRWebSocket.o
FAILED: obj/examples/socketrocket/SRWebSocket.o
../../buildtools/reclient/rewrapper -cfg=../../buildtools/reclient_cfgs/chromium-browser-clang/rewrapper_mac.cfg -exec_root=/Volumes/Work/s/w/...(too long)
../../examples/objc/AppRTCMobile/third_party/SocketRocket/SRWebSocket.m:1083:75: error: arithmetic on a pointer to void is a GNU extension [-Werror,-Wgnu-pointer-arith]
1083 |         NSInteger bytesWritten = [_outputStream write:_outputBuffer.bytes + _outputBufferOffset maxLength:dataLength - _outputBufferOffset];
|                                                       ~~~~~~~~~~~~~~~~~~~ ^
1 error generated.
```
#### [Click here for more information](https://logs.chromium.org/logs/webrtc/buildbucket/cr-buildbucket/8731920573171442705/+/u/compile/raw_io.output_text_failure_summary_)

---
* [webrtc/try/mac_compile_dbg](https://cr-buildbucket.appspot.com/build/8731920573171442673). Summary ([view all results](https://webrtc-review.googlesource.com/c/367865?checksPatchset=1&tab=checks)):

---
#### Step _compile_ failed. Error logs are shown below:
```
[2894/4689] OBJC obj/examples/socketrocket/SRWebSocket.o
FAILED: obj/examples/socketrocket/SRWebSocket.o
../../buildtools/reclient/rewrapper -cfg=../../buildtools/reclient_cfgs/chromium-browser-clang/rewrapper_mac.cfg -exec_root=/Volumes/Work/s/w/...(too long)
../../examples/objc/AppRTCMobile/third_party/SocketRocket/SRWebSocket.m:1083:75: error: arithmetic on a pointer to void is a GNU extension [-Werror,-Wgnu-pointer-arith]
1083 |         NSInteger bytesWritten = [_outputStream write:_outputBuffer.bytes + _outputBufferOffset maxLength:dataLength - _outputBufferOffset];
|                                                       ~~~~~~~~~~~~~~~~~~~ ^
1 error generated.
```
#### [Click here for more information](https://logs.chromium.org/logs/webrtc/buildbucket/cr-buildbucket/8731920573171442673/+/u/compile/raw_io.output_text_failure_summary_)

---

Patch-set: 1
Tag: autogenerated:cq:full-run:1730988635