Update patch set 1
Patch Set 1:

This CL has failed the run. Reason:

Failed Tryjobs:
* [webrtc/try/android_compile_x86_rel](https://cr-buildbucket.appspot.com/build/8770303920871464449). Summary:

---
#### Step _generate_build_files_ failed. Error logs are shown below:
```
ERROR at //build/config/android/jni.gni:22:44: Undefined identifier
       invoker.manual_jni_registration) || allow_jni_multiplexing
                                           ^---------------------
See //build/config/android/jni.gni:81:3: whence it was called.
  _native_with_jni(target_name) {
  ^------------------------------
See //testing/test.gni:140:3: whence it was called.
  target(invoker.target_type, target_name) {
  ^-----------------------------------------
See //testing/test.gni:390:7: whence it was called.
      mixed_test(_library_target_name) {
      ^---------------------------------
See //webrtc.gni:505:3: whence it was called.
  test(target_name) {
  ^------------------
```
##### ...The message was too long...
#### More information can be found in the stdout.

---
* [webrtc/try/ios_compile_arm64_rel](https://cr-buildbucket.appspot.com/build/8770303920871464385). Summary:

---
#### Step _compile_ failed. Error logs are shown below:
```
[1/17] OBJC obj/sdk/sdk_unittests_sources/RTCMTLVideoView_xctest.o
FAILED: obj/sdk/sdk_unittests_sources/RTCMTLVideoView_xctest.o
../../buildtools/reclient/rewrapper -cfg=../../buildtools/reclient_cfgs/chromium-browser-clang/rewra...(too long)
../../sdk/objc/unittests/RTCMTLVideoView_xctest.m:295:13: error: expression result unused [-Werror,-Wunused-value]
295 |   OCMVerify(metalKitView);
|             ^~~~~~~~~~~~
../../third_party/ocmock/OCMock/OCMockMacros.h:146:93: note: expanded from macro 'OCMVerify'
146 | #define OCMVerify(...) _OCMVerify_X(,##__VA_ARGS__, _OCMVerify_2(__VA_ARGS__), _OCMVerify_1(__VA_ARGS__))
```
##### ...The message was too long...
#### More information in raw_io.output_text[failure_summary]

---

Patch-set: 1
Tag: autogenerated:cq:full-run:1694383420