Fix android_arm_rel on Chromium Roll.
Error: https://ci.chromium.org/p/webrtc/builders/try/android_arm_rel/18894

  Exception: Missing licenses for following third_party targets: nasm

No-Try: True
Bug: None
Change-Id: I2b916d3063ca3019ec3fa473b9ba4375905f538b