Update patch set 2
Patch Set 2:

Dry run: Try jobs failed on following builders:
  luci.webrtc.try/presubmit JOB_FAILED https://ci.chromium.org/b/8894916408014437904
    There are 1 error(s), 0 warning(s), and 12 notifications(s). Here are the errors:
    
    **ERROR**
    
    Bug entry requires issue tracker prefix, e.g. chromium:1031013
    
    
    
    To see notifications and warnings, look at the stdout of the presubmit step.
  luci.webrtc.try/ios_compile_arm64_dbg JOB_FAILED https://ci.chromium.org/b/8894916408014437536
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [111/231] CXX obj/pc/peerconnection/video_rtp_receiver.o
    FAILED: obj/pc/peerconnection/video_rtp_receiver.o
    /b/s/w/ir/cache/goma/client/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF...(too long)
    ../../pc/video_rtp_receiver.cc:158:3: error: use of undeclared identifier 'DCHECK'
    DCHECK(media_channel_);
    ^
    1 error generated.
    ```
    #### More information in raw_io.output[failure_summary]
  luci.webrtc.try/ios_sim_x64_dbg_ios11 JOB_FAILED https://ci.chromium.org/b/8894916408014437408
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [297/496] CXX obj/pc/peerconnection/video_rtp_receiver.o
    FAILED: obj/pc/peerconnection/video_rtp_receiver.o
    /b/s/w/ir/cache/goma/client/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF...(too long)
    ../../pc/video_rtp_receiver.cc:158:3: error: use of undeclared identifier 'DCHECK'
    DCHECK(media_channel_);
    ^
    1 error generated.
    ```
    #### More information in raw_io.output[failure_summary]
  luci.webrtc.try/mac_compile_dbg JOB_FAILED https://ci.chromium.org/b/8894916408014437472
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [367/433] CXX obj/pc/peerconnection/video_rtp_receiver.o
    FAILED: obj/pc/peerconnection/video_rtp_receiver.o
    /b/s/w/ir/cache/goma/client/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF...(too long)
    ../../pc/video_rtp_receiver.cc:158:3: error: use of undeclared identifier 'DCHECK'
    DCHECK(media_channel_);
    ^
    1 error generated.
    ```
    #### More information in raw_io.output[failure_summary]
  luci.webrtc.try/mac_rel JOB_FAILED https://ci.chromium.org/b/8894916408014437136
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [14/47] CXX obj/pc/peerconnection/video_rtp_receiver.o
    FAILED: obj/pc/peerconnection/video_rtp_receiver.o
    /b/s/w/ir/cache/goma/client/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF...(too long)
    ../../pc/video_rtp_receiver.cc:158:3: error: use of undeclared identifier 'DCHECK'
    DCHECK(media_channel_);
    ^
    1 error generated.
    ```
    #### More information in raw_io.output[failure_summary]
  luci.webrtc.try/linux_x86_dbg JOB_FAILED https://ci.chromium.org/b/8894916408014437728
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [68/81] CXX obj/pc/peerconnection/video_rtp_receiver.o
    FAILED: obj/pc/peerconnection/video_rtp_receiver.o
    /b/s/w/ir/cache/goma/client/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF...(too long)
    ../../pc/video_rtp_receiver.cc:158:3: error: use of undeclared identifier 'DCHECK'
    DCHECK(media_channel_);
    ^
    1 error generated.
    ```
    #### More information in raw_io.output[failure_summary]
  luci.webrtc.try/linux_ubsan_vptr JOB_FAILED https://ci.chromium.org/b/8894916408014437504
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [68/81] CXX obj/pc/peerconnection/video_rtp_receiver.o
    FAILED: obj/pc/peerconnection/video_rtp_receiver.o
    /b/s/w/ir/cache/goma/client/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF...(too long)
    ../../pc/video_rtp_receiver.cc:158:3: error: use of undeclared identifier 'DCHECK'
    DCHECK(media_channel_);
    ^
    1 error generated.
    ```
    #### More information in raw_io.output[failure_summary]
  luci.webrtc.try/ios_compile_arm64_rel JOB_FAILED https://ci.chromium.org/b/8894916408014437840
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [235/390] CXX obj/pc/peerconnection/video_rtp_receiver.o
    FAILED: obj/pc/peerconnection/video_rtp_receiver.o
    /b/s/w/ir/cache/goma/client/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF...(too long)
    ../../pc/video_rtp_receiver.cc:158:3: error: use of undeclared identifier 'DCHECK'
    DCHECK(media_channel_);
    ^
    1 error generated.
    ```
    #### More information in raw_io.output[failure_summary]
  luci.webrtc.try/android_compile_x86_rel JOB_FAILED https://ci.chromium.org/b/8894916408014437744
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [1/330] CXX obj/pc/peerconnection/video_rtp_receiver.o
    FAILED: obj/pc/peerconnection/video_rtp_receiver.o
    /b/s/w/ir/cache/goma/client/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF...(too long)
    ../../pc/video_rtp_receiver.cc:158:3: error: use of undeclared identifier 'DCHECK'
    DCHECK(media_channel_);
    ^
    1 error generated.
    ```
    #### More information in raw_io.output[failure_summary]

Patch-set: 2
Tag: autogenerated:cq:dry-run